#!/usr/bin/env bash

rm ~/.vim
rm ~/.vimrc
rm ~/.gvimrc

ln -s $(pwd)/vim/vimrc ~/.vimrc
ln -s $(pwd)/vim/gvimrc ~/.gvimrc
ln -s $(pwd)/git/gitconfig ~/.gitconfig
ln -s $(pwd)/git/gitignore ~/.gitignore
ln -s $(pwd)/git/gitattributes ~/.gitattributes
ln -s $(pwd)/git/git_template ~/.git_template
ln -s $(pwd)/tmux.conf ~/.tmux.conf
