function! Fullscreen()
	set columns=271
	set lines=82
endfunction

function! Halfscreen()
	set columns=135
	set lines=82
endfunction

" OS Specific 
if has("gui_macvim")
  " fullscreen options (MacVim only), resized window when changed to fullscreen
	call Halfscreen()
  set fuoptions=maxvert,maxhorz 
  "set guifont=Monaco:h13
  "set guifont=ProggyClean:h11
	set guifont=Inconsolata:h14
  set guioptions-=T  " remove toolbar
  set stal=2 " turn on tabs by default
elseif has("gui_gtk2")
  set guifont=Monaco
  set guioptions-=T  " remove toolbar
elseif has("x11")
elseif has("gui_win32")
end

" Disable the intro message
set shortmess+=I

" General 
set anti " Antialias font
"set transparency=0

" Default size of window
"set columns=115 
"set lines=54

" Tab headings 
set gtl=%t gtt=%F
