" -----------------------------------------------------------------------------  
" |                            VIM Settings                                   |
" |                   (see gvimrc for gui vim settings)                       |
" |                                                                           |
" | Some highlights:                                                          |
" |   jj = <esc>  Very useful for keeping your hands on the home row          |
" |                                                                           |
" |   ,f = fuzzy find all files                                               |
" |   ,b = fuzzy find in all buffers                                          |
" |                                                                           |
" |   hh = inserts '=>'                                                       |
" |   aa = inserts '@'                                                        |
" |                                                                           |
" |   ,h = new horizontal window                                              |
" |   ,v = new vertical window                                                |
" |                                                                           |
" |   ,i = toggle invisibles                                                  |
" |                                                                           |
" |   enter and shift-enter = adds a new line after/before the current line   |
" |                                                                           |
" |   :call Tabstyle_tabs = set tab to real tabs                              |
" |   :call Tabstyle_spaces = set tab to 2 spaces                             |
" |                                                                           |
" | Put machine/user specific settings in ~/.vimrc.local                      |
" -----------------------------------------------------------------------------  
set nocompatible

silent! call pathogen#helptags()
silent! call pathogen#runtime_append_all_bundles()

function! Tabstyle_tabs()
  set softtabstop=2
  set shiftwidth=2
  set tabstop=2
  set noexpandtab
endfunction

function! Tabstyle_spaces()
  " Use 2 spaces
  set softtabstop=2
  set shiftwidth=2
  set tabstop=2
  set expandtab
endfunction

"call Tabstyle_spaces()
call Tabstyle_tabs()

let mapleader = ","

set ai " Automatically set the indent of a new line (local to buffer)
set si " smartindent	(local to buffer)
set sidescrolloff=2
set numberwidth=4
set title " Show title in console title bar
set ttyfast " Smoother changes
"set foldmethod=syntax " Set the code folding method based on the language syntax
set equalalways " Multiple windows, when created, are equal in size
set splitbelow splitright
set cursorline
set hlsearch  " highlight search
set incsearch  " incremental search, search as you type
set ignorecase " Ignore case when searching 
set smartcase " Ignore case when searching lowercase
set background=dark 
set showcmd
set statusline=%F%m%r%h%w\ [TYPE=%Y\ %{&ff}]\ %{fugitive#statusline()}\ [%l/%L\ (%p%%)]
set ls=2
set wrap
set formatoptions=1
set lbr
set listchars=trail:.,tab:>-,eol:$
set nolist
set backspace=indent,eol,start
set matchpairs+=<:>
set vb t_vb= " Turn off bell, this could be more annoying, but I'm not sure how
set sessionoptions=blank,buffers,curdir,folds,help,resize,tabpages,winsize

" Prevent junk/swap files
set nobackup
set nowritebackup
set noswapfile

let g:loaded_matchparen= 1 " Turn off matching braces

syntax on
colorscheme ir_dark

:noremap ,v :vsp^M^W^W<cr>	" vertical split then to new buffer
:noremap ,h :split^M^W^W<cr>	" horizontal split then to new buffer
:noremap ,i :set list!<CR> " Toggle invisible chars

match LongLineWarning '\%120v.*' " Error format when a line is longer than 120

" Mappings
imap jj <Esc>
imap uu _
imap hh =>
imap aa @
map <up> gk
map k gk
imap <up> <C-o>gk
map <down> gj
map j gj
imap <down> <C-o>gj
map E ge
map <S-Enter> O<ESC> " inserts new line without going into insert mode
map <Enter> o<ESC>

" Allows :w!! to write a file using sudo if you forgot to sudo vim <file>
cmap w!! %!sudo tee > /dev/null %

" File Stuff
filetype plugin indent on
au BufNewFile,BufRead *.install set filetype=php
au BufNewFile,BufRead *.module set filetype=php
autocmd FileType html :set filetype=xhtml 

" When editing a file, always jump to the last cursor position
autocmd BufReadPost *
\ if ! exists("g:leave_my_cursor_position:alone") |
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "normal g'\"" |
\ endif |
\ endif

" Automatically source .vimrc when changes are made
if has("autocmd")
	autocmd BufWritePost .vimrc source $MYVIMRC
endif

autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete 

" Plugins
let g:AutoComplPop_IgnoreCaseOption = 0
let g:AutoComplPop_BehaviorKeywordLength = 2
nmap <silent> <C-n> :NERDTreeToggle<CR>

let g:user_zen_settings = {
\ 'php' : {
\ 'extends' : 'html',
\ 'filters' : 'c',
\ },
\ 'xml' : {
\ 'extends' : 'html',
\ },
\ 'haml' : {
\ 'extends' : 'html',
\ },
\}
