" -----------------------------------------------------------------------------  
" |                            VIM Settings                                   |
" |                   (see gvimrc for gui vim settings)                       |
" |                                                                           |
" | Some highlights:                                                          |
" |   jj = <esc>  Very useful for keeping your hands on the home row          |
" |                                                                           |
" |   ,f = fuzzy find all files                                               |
" |   ,b = fuzzy find in all buffers                                          |
" |                                                                           |
" |   hh = inserts '=>'                                                       |
" |   aa = inserts '@'                                                        |
" |                                                                           |
" |   ,h = new horizontal window                                              |
" |   ,v = new vertical window                                                |
" |                                                                           |
" |   ,i = toggle invisibles                                                  |
" |                                                                           |
" |   enter and shift-enter = adds a new line after/before the current line   |
" |                                                                           |
" |   :call Tabstyle_tabs = set tab to real tabs                              |
" |   :call Tabstyle_spaces = set tab to 2 spaces                             |
" |                                                                           |
" | Put machine/user specific settings in ~/.vimrc.local                      |
" -----------------------------------------------------------------------------  
set nocompatible

silent! call pathogen#helptags()
silent! call pathogen#runtime_append_all_bundles()

function! Tabstyle_tabs()
  set softtabstop=2
  set shiftwidth=2
  set tabstop=2
  set noexpandtab
endfunction

function! Tabstyle_spaces()
  " Use 2 spaces
  set softtabstop=2
  set shiftwidth=2
  set tabstop=2
  set expandtab
endfunction

"call Tabstyle_spaces()
call Tabstyle_tabs()

let mapleader = ","

set ai " Automatically set the indent of a new line (local to buffer)
set si " smartindent	(local to buffer)
set sidescrolloff=2
set numberwidth=4
set title " Show title in console title bar
set ttyfast " Smoother changes
"set foldmethod=syntax " Set the code folding method based on the language syntax
set equalalways " Multiple windows, when created, are equal in size
set splitbelow splitright
set cursorline
set hlsearch  " highlight search
set incsearch  " incremental search, search as you type
set ignorecase " Ignore case when searching 
set smartcase " Ignore case when searching lowercase
set background=dark 
set showcmd
set statusline=%F%m%r%h%w\ [TYPE=%Y\ %{&ff}]\ %{fugitive#statusline()}\ [%c\ %l/%L\ (%p%%)]
set ls=2
set wrap
set formatoptions=qrn1
set lbr
set listchars=trail:.,tab:>-,eol:$
set nolist
set backspace=indent,eol,start
set matchpairs+=<:>
set vb t_vb= " Turn off bell, this could be more annoying, but I'm not sure how
set sessionoptions=blank,buffers,curdir,folds,help,resize,tabpages,winsize

" Prevent junk/swap files
set nobackup
set nowritebackup
set noswapfile

let g:loaded_matchparen= 1 " Turn off matching braces

syntax on
colorscheme ir_dark

" Turn off vim's default regex characters
nnoremap / /\v
vnoremap / /\v

" Vertical split then to new buffer
nnoremap <leader>v <C-w>v<C-w>l
nnoremap <leader>i :set list!<cr> " Toggle invisible chars

" Clear recent search highlighting
nnoremap <leader><space> :noh<cr>

" Make the tab key match braces
nnoremap <tab> %
vnoremap <tab> %

" Easily navigate around splits
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Allows :w!! to write a file using sudo if you forgot to sudo vim <file>
cnoremap w!! %!sudo tee > /dev/null %

" Other Mappings
inoremap jj <Esc>
inoremap uu _
inoremap hh =>
inoremap aa @
inoremap <up> <C-o>gk
inoremap <down> <C-o>gj
noremap <up> gk
noremap k gk
noremap <down> gj
noremap j gj
noremap E ge
noremap <S-Enter> O<ESC> " inserts new line without going into insert mode
noremap <Enter> o<ESC>

" Error format when a line is longer than 120
match LongLineWarning '\%120v.*'

" File Stuff
filetype plugin indent on
au BufNewFile,BufRead *.install set filetype=php
au BufNewFile,BufRead *.module set filetype=php
autocmd FileType html :set filetype=xhtml 

" When editing a file, always jump to the last cursor position
autocmd BufReadPost *
\ if ! exists("g:leave_my_cursor_position:alone") |
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "normal g'\"" |
\ endif |
\ endif

" Automatically source .vimrc when changes are made
if has("autocmd")
	autocmd BufWritePost .vimrc source $MYVIMRC
endif

autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete 

" Debug PHP code with :pc
cabbr pc !php -l %

" Plugins
let g:AutoComplPop_IgnoreCaseOption = 0
let g:AutoComplPop_BehaviorKeywordLength = 2
nnoremap <silent> <C-n> :NERDTreeToggle<CR>
nnoremap <leader>a :Ack
nnoremap <leader><tab> :Scratch

let g:user_zen_settings = {
\ 'php' : {
\ 'extends' : 'html',
\ 'filters' : 'c',
\ },
\ 'xml' : {
\ 'extends' : 'html',
\ },
\ 'haml' : {
\ 'extends' : 'html',
\ },
\}
