# Shamlessly stolen from twerth @ infinitered
# http://www.infinitered.com/blog/?p=10 for more details
# Note, default OS is assumed to be OSX

# Load .bashrc 
source ~/.bashrc

# Turn on advanced bash completion if the file exists 
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Identify OS and Machine
export OS=`uname -s | sed -e 's/  */-/g;y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'`
export OSVERSION=`uname -r`; OSVERSION=`expr "$OSVERSION" : '[^0-9]*\([0-9]*\.[0-9]*\)'`
export MACHINE=`uname -m | sed -e 's/  */-/g;y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'`
export PLATFORM="$MACHINE-$OS-$OSVERSION"

[[ -d ~/bin ]] && PATH="$HOME/bin:$PATH"

# Path 
if [ "$OS" = "darwin" ] ; then
  PATH="/usr/local/bin:/usr/local/sbin:$PATH"
  PATH="$PATH:/usr/local/mysql/bin"
fi

export PATH=$PATH

# Welcome message
if [ "$OS" = "darwin" ] ; then
	echo -e "`fortune | cowsay`"
else
	echo -e "Kernel Information: " `uname -smr`
	echo -e "`bash --version`"
	echo -ne "Uptime: "; uptime
	echo -ne "Server time is: "; date
fi

# Source RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

# Notes: 
# When you start an interactive shell (log in, open terminal or iTerm in OS X, 
# or create a new tab in iTerm) the following files are read and run, in this order:
#     profile
#     bashrc
#     .bash_profile
#     .bashrc (only because this file is run (sourced) in .bash_profile)
#
# When an interactive shell, that is not a login shell, is started 
# (when you run "bash" from inside a shell, or when you start a shell in 
# xwindows [xterm/gnome-terminal/etc] ) the following files are read and executed, 
# in this order:
#     bashrc
#     .bashrc
