# Files
alias reloadbash="source ~/.bash_profile"
alias profile="$EDITOR ~/.bash_profile"
alias rc="$EDITOR ~/.bashrc"
alias aliases="$EDITOR ~/.bash_aliases"

# MySQL
#alias startmy="sudo launchctl load -w /Library/LaunchDaemons/com.mysql.mysqld.plist"
#alias stopmy="sudo launchctl unload -w /Library/LaunchDaemons/com.mysql.mysqld.plist"

# History
alias h="history"
hs() { h | grep $1; }

# Git
alias ga="git add"
alias gb="git branch"
alias gba="git branch -a"
alias gc="git commit"
alias gcaa="git commit -a --amend -C HEAD" # Put changes into the previous commit using the previous commit message
alias gcm="git commit -am"
alias gco="git checkout"
alias gd="git diff"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias glt="git cat-file commit HEAD" # Show information about the last commit
alias gph="git push"
alias gpl="git pull"
alias gs="git status -s" # Short status of repo
alias gsl="git shortlog -s --"

# General
alias ll="ls -lG"
alias la="ls -AG"
alias l="ls -aCFG"
alias ls="ls -G" # OSX only
alias a="ls -alG"
alias s="cd .."
alias ..="cd .."
alias ...="cd .. ; cd .."
alias q="exit"
alias c="clear"
cl() { cd $1; ls -al; }

# Search 
alias g="grep -i"  # Case insensitive grep
gns() { # Case insensitive, excluding git folders
  find . -path '*/.git' -prune -o -type f -print0 | xargs -0 grep -I -n -e '$1'
}
alias f="find . -iname"

# Misc
alias colorslist="set | egrep 'COLOR_\w*'" # lists all the colors
alias ducks="du -cksh * | sort -rn | head -11" # Lists folders and files sizes in the current folder
alias systail="tail -f /var/log/system.log"
alias m="mvim"
alias v="vim"
alias df="df -h" # Show disk usage
alias top="top -o cpu" # OSX only
alias show="cat ~/.dirs"
save () {
  command sed "/!$/d" ~/.dirs > ~/.dirs1; \mv ~/.dirs1 ~/.dirs; echo "$@"=\"`pwd`\" >> ~/.dirs; source ~/.dirs ; 
}

# Shows most used commands
alias profileme="history | awk '{print \$2}' | awk 'BEGIN{FS=\"|\"}{print \$1}' | sort | uniq -c | sort -n | tail -n 20 | sort -nr"
# Copies folder and all sub files and folders, preserving security and dates
alias cpf="cp -Rpv" 
